### ISSUE TITLE
Registering parameterized flows fails on 2022.01.12

### ISSUE THREAD

**Issue by kgorszczyk** [PrefectHQ/server#338]
## Description

After updating to Server Version 2022.01.12 (with Hasura v2.0.9) and all agents to Version 0.15.12 I can no longer register a flow, where a parameter value is used in a subsequent task. My GraphQL Container reports the folloring error:

> [{'extensions': {'path': '$.selectionSet.insert_edge.args.on_conflict.constraint', 'code': 'validation-failed'}, 'message': 'expected one of the values edge_pkey for type "edge_constraint", but found "edge_flow_id_task_ids_key"'}]
> GraphQL request:2:3
> 1 | mutation ($input: register_edges_input!) {
> 2 |   register_edges(input: $input) {
>   |   ^
> 3 |     success
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 668, in await_completed
>     return await completed
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 653, in await_result
>     return_type, field_nodes, info, path, await result
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 727, in complete_value
>     raise result
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 626, in await_result
>     return await result
> INFO:     10.1.128.85:55096 - "POST /graphql/ HTTP/1.1" 200 OK
>   File "/prefect-server/src/prefect_server/graphql/extensions.py", line 52, in resolve
>     result = await result
>   File "/prefect-server/src/prefect_server/graphql/flows.py", line 111, in resolve_register_edges
>     flow_id=flow_id, tenant_id=None, serialized_edges=serialized_edges
>   File "/prefect-server/src/prefect_server/api/flows.py", line 368, in register_edges
>     constraint="edge_flow_id_task_ids_key", update_columns=[]
>   File "/prefect-server/src/prefect_server/database/orm.py", line 318, in insert_many
>     insert_mutation_name=cls.__root_fields__.get("insert"),
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 237, in insert
>     result = await self.execute_mutations_in_transaction(mutations=[graphql])
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 165, in execute_mutations_in_transaction
>     as_box=as_box,
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 85, in execute
>     as_box=as_box,
>   File "/prefect-server/src/prefect_server/utilities/graphql.py", line 84, in execute
>     raise ValueError(result["errors"])
> ValueError: [{'extensions': {'path': '$.selectionSet.insert_edge.args.on_conflict.constraint', 'code': 'validation-failed'}, 'message': 'expected one of the values edge_pkey for type "edge_constraint", but found "edge_flow_id_task_ids_key"'}]
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 668, in await_completed
>     return await completed
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 653, in await_result
>     return_type, field_nodes, info, path, await result
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 727, in complete_value
>     raise result
>   File "/usr/local/lib/python3.7/site-packages/graphql/execution/execute.py", line 626, in await_result
>     return await result
>   File "/prefect-server/src/prefect_server/graphql/extensions.py", line 52, in resolve
>     result = await result
>   File "/prefect-server/src/prefect_server/graphql/flows.py", line 111, in resolve_register_edges
>     flow_id=flow_id, tenant_id=None, serialized_edges=serialized_edges
>   File "/prefect-server/src/prefect_server/api/flows.py", line 368, in register_edges
>     constraint="edge_flow_id_task_ids_key", update_columns=[]
>   File "/prefect-server/src/prefect_server/database/orm.py", line 318, in insert_many
>     insert_mutation_name=cls.__root_fields__.get("insert"),
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 237, in insert
>     result = await self.execute_mutations_in_transaction(mutations=[graphql])
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 165, in execute_mutations_in_transaction
>     as_box=as_box,
>   File "/prefect-server/src/prefect_server/database/hasura.py", line 85, in execute
>     as_box=as_box,
>   File "/prefect-server/src/prefect_server/utilities/graphql.py", line 84, in execute
>     raise ValueError(result["errors"])
> graphql.error.graphql_error.GraphQLError: [{'extensions': {'path': '$.selectionSet.insert_edge.args.on_conflict.constraint', 'code': 'validation-failed'}, 'message': 'expected one of the values edge_pkey for type "edge_constraint", but found "edge_flow_id_task_ids_key"'}]
> GraphQL request:2:3
> 1 | mutation ($input: register_edges_input!) {
> 2 |   register_edges(input: $input) {
>   |   ^
> 3 |     success

Same behaviour with my previously used flows. When I disable the parameter the flow registers successfully. 

## Expected Behavior

Flow registers successfully

## Reproduction

```
@task
def print_plus_one(x):
    print(x + 1)

with Flow('Parameterized Flow') as flow:
    x = Parameter('x', default = 2)
    print_plus_one(x=x)

# Register the flow under the "tutorial" project
flow.register(project_name="tutorial")
```
(https://docs.prefect.io/core/concepts/parameters.html)

## Environment

```
prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-96-generic-x86_64-with-glibc2.29",
    "prefect_backend": "server",
    "prefect_version": "0.15.12",
    "python_version": "3.8.10"
  }
}
```

Server/Apollo Version: 2022.01.12
Hasura Version: v2.0.9
Agents: 0.15.12

**Comment by kgorszczyk** [comment]
I figured it out. It seems that the GraphQL Container didn't automatically update the database to the newest version. The command: `prefect-server database upgrade --yes ` solved my problem
